name = "mailfree-openapi"
main = "src/openapi/server.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free_db"
database_id = "030eaf04-d420-474a-af23-31585e0731a2"

[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"

[vars]
# OPENAPI_API_KEY = "k_xxx"
# OPENAPI_DEFAULT_ROLE = "CIVILIAN"
# OPENAPI_ADMIN_CONTACT = ""
# OPENAPI_MAX_EMAILS = "10"
# MAIL_DOMAIN = "temp.example.com"
